import type { Question } from './types';

export const questions: Question[] = [
  {
    id: 1,
    text: 'Pick the image that speaks to you',
    type: 'image',
    options: [
      { id: 0, label: 'Sunset Peaks', gradient: 'linear-gradient(135deg, #ff6b35, #f7c948, #ff8c42)' },
      { id: 1, label: 'Ocean Deep', gradient: 'linear-gradient(135deg, #0077b6, #023e8a, #48cae4)' },
      { id: 2, label: 'Forest Canopy', gradient: 'linear-gradient(135deg, #2d6a4f, #40916c, #95d5b2)' },
      { id: 3, label: 'Northern Lights', gradient: 'linear-gradient(135deg, #7209b7, #3a0ca3, #4cc9f0)' },
    ],
    dimensionWeights: {
      0: { energy: 85, warmth: 90, luminance: 75, depth: 40 },
      1: { energy: 30, warmth: 25, luminance: 40, depth: 90 },
      2: { energy: 45, warmth: 65, luminance: 55, depth: 70 },
      3: { energy: 70, warmth: 35, luminance: 65, depth: 85 },
    },
  },
  {
    id: 2,
    text: 'Choose a word',
    type: 'word',
    options: [
      { id: 0, label: 'Ignite' },
      { id: 1, label: 'Flow' },
      { id: 2, label: 'Ground' },
      { id: 3, label: 'Expand' },
    ],
    dimensionWeights: {
      0: { energy: 95, warmth: 80, rhythm: 75, complexity: 50 },
      1: { energy: 40, warmth: 60, rhythm: 70, complexity: 35 },
      2: { energy: 25, warmth: 55, rhythm: 30, complexity: 25 },
      3: { energy: 65, warmth: 45, rhythm: 55, complexity: 80 },
    },
  },
  {
    id: 3,
    text: 'Your ideal morning?',
    type: 'image',
    options: [
      { id: 0, label: 'Sunrise Run', gradient: 'linear-gradient(135deg, #f72585, #ff758f, #ffb3c6)' },
      { id: 1, label: 'Coffee & Rain', gradient: 'linear-gradient(135deg, #6c584c, #a98467, #ddb892)' },
      { id: 2, label: 'Yoga at Dawn', gradient: 'linear-gradient(135deg, #ffd166, #ef8354, #f4845f)' },
      { id: 3, label: 'Sleep In', gradient: 'linear-gradient(135deg, #2b2d42, #3d405b, #8d99ae)' },
    ],
    dimensionWeights: {
      0: { rhythm: 90, warmth: 70, energy: 85 },
      1: { rhythm: 40, warmth: 80, energy: 30 },
      2: { rhythm: 65, warmth: 75, energy: 50 },
      3: { rhythm: 15, warmth: 50, energy: 15 },
    },
  },
  {
    id: 4,
    text: 'Pick a texture',
    type: 'image',
    options: [
      { id: 0, label: 'Smooth Glass', gradient: 'linear-gradient(135deg, #e0fbfc, #c2dfe3, #9db4c0)' },
      { id: 1, label: 'Rough Stone', gradient: 'linear-gradient(135deg, #6b705c, #a5a58d, #b6ad90)' },
      { id: 2, label: 'Flowing Water', gradient: 'linear-gradient(135deg, #48cae4, #0096c7, #023e8a)' },
      { id: 3, label: 'Crackling Fire', gradient: 'linear-gradient(135deg, #e63946, #f4a261, #e76f51)' },
    ],
    dimensionWeights: {
      0: { complexity: 15, rhythm: 50, depth: 30, energy: 25 },
      1: { complexity: 60, rhythm: 25, depth: 75, energy: 35 },
      2: { complexity: 45, rhythm: 80, depth: 55, energy: 50 },
      3: { complexity: 80, rhythm: 65, depth: 40, energy: 90 },
    },
  },
  {
    id: 5,
    text: 'What draws your eye?',
    type: 'image',
    options: [
      { id: 0, label: 'Geometric', gradient: 'linear-gradient(45deg, #000 25%, #fff 25%, #fff 50%, #000 50%, #000 75%, #fff 75%)' },
      { id: 1, label: 'Organic', gradient: 'radial-gradient(ellipse at 30% 50%, #2d6a4f, #40916c, #b7e4c7)' },
      { id: 2, label: 'Chaotic', gradient: 'conic-gradient(from 45deg, #e63946, #457b9d, #f1faee, #a8dadc, #e63946)' },
      { id: 3, label: 'Minimal', gradient: 'linear-gradient(180deg, #fafafa 0%, #f0f0f0 100%)' },
    ],
    dimensionWeights: {
      0: { complexity: 65, rhythm: 70, depth: 50 },
      1: { complexity: 45, rhythm: 55, depth: 65 },
      2: { complexity: 90, rhythm: 40, depth: 75 },
      3: { complexity: 15, rhythm: 45, depth: 30 },
    },
  },
  {
    id: 6,
    text: 'Choose an element',
    type: 'icon',
    options: [
      { id: 0, label: 'Fire', icon: '🔥' },
      { id: 1, label: 'Water', icon: '🌊' },
      { id: 2, label: 'Earth', icon: '🌿' },
      { id: 3, label: 'Air', icon: '💨' },
    ],
    dimensionWeights: {
      0: { energy: 90, warmth: 90, luminance: 70, depth: 35 },
      1: { energy: 35, warmth: 40, luminance: 50, depth: 80 },
      2: { energy: 30, warmth: 65, luminance: 40, depth: 70 },
      3: { energy: 60, warmth: 30, luminance: 85, depth: 45 },
    },
  },
  {
    id: 7,
    text: 'Your energy right now?',
    type: 'slider',
    options: [
      { id: 0, label: 'Still' },
      { id: 1, label: 'Calm' },
      { id: 2, label: 'Steady' },
      { id: 3, label: 'Buzzing' },
      { id: 4, label: 'Electric' },
    ],
    dimensionWeights: {
      0: { energy: 10, rhythm: 10 },
      1: { energy: 30, rhythm: 30 },
      2: { energy: 50, rhythm: 50 },
      3: { energy: 75, rhythm: 75 },
      4: { energy: 95, rhythm: 90 },
    },
  },
  {
    id: 8,
    text: 'Pick the sound',
    type: 'icon',
    options: [
      { id: 0, label: 'Rain', icon: '🌧️' },
      { id: 1, label: 'Thunder', icon: '⚡' },
      { id: 2, label: 'Wind Chimes', icon: '🎐' },
      { id: 3, label: 'Silence', icon: '🤫' },
    ],
    dimensionWeights: {
      0: { complexity: 40, depth: 65, rhythm: 55, warmth: 55 },
      1: { complexity: 85, depth: 50, rhythm: 70, warmth: 40 },
      2: { complexity: 55, depth: 45, rhythm: 75, warmth: 70 },
      3: { complexity: 20, depth: 85, rhythm: 20, warmth: 45 },
    },
  },
  {
    id: 9,
    text: 'Light or dark?',
    type: 'slider',
    options: [
      { id: 0, label: 'Deep Dark' },
      { id: 1, label: 'Dim' },
      { id: 2, label: 'Balanced' },
      { id: 3, label: 'Bright' },
      { id: 4, label: 'Radiant' },
    ],
    dimensionWeights: {
      0: { luminance: 10, depth: 90 },
      1: { luminance: 30, depth: 70 },
      2: { luminance: 50, depth: 50 },
      3: { luminance: 75, depth: 35 },
      4: { luminance: 95, depth: 15 },
    },
  },
  {
    id: 10,
    text: 'What season feels most like you?',
    type: 'icon',
    options: [
      { id: 0, label: 'Spring', icon: '🌸' },
      { id: 1, label: 'Summer', icon: '☀️' },
      { id: 2, label: 'Autumn', icon: '🍂' },
      { id: 3, label: 'Winter', icon: '❄️' },
    ],
    dimensionWeights: {
      0: { warmth: 65, energy: 60, luminance: 75, rhythm: 60 },
      1: { warmth: 90, energy: 80, luminance: 85, rhythm: 70 },
      2: { warmth: 55, energy: 40, luminance: 45, rhythm: 45 },
      3: { warmth: 20, energy: 25, luminance: 30, rhythm: 30 },
    },
  },
  {
    id: 11,
    text: 'Your mind is more like...',
    type: 'image',
    options: [
      { id: 0, label: 'Ocean', gradient: 'linear-gradient(180deg, #0077b6, #00b4d8, #90e0ef)' },
      { id: 1, label: 'Forest', gradient: 'linear-gradient(180deg, #1b4332, #2d6a4f, #52b788)' },
      { id: 2, label: 'Desert', gradient: 'linear-gradient(180deg, #e9c46a, #f4a261, #e76f51)' },
      { id: 3, label: 'City', gradient: 'linear-gradient(180deg, #2b2d42, #3d405b, #ef233c)' },
    ],
    dimensionWeights: {
      0: { complexity: 60, depth: 85, warmth: 40 },
      1: { complexity: 50, depth: 70, warmth: 60 },
      2: { complexity: 30, depth: 40, warmth: 75 },
      3: { complexity: 90, depth: 55, warmth: 35 },
    },
  },
  {
    id: 12,
    text: 'Final vibe check — one word',
    type: 'word',
    options: [
      { id: 0, label: 'Serene' },
      { id: 1, label: 'Bold' },
      { id: 2, label: 'Mystic' },
      { id: 3, label: 'Wild' },
    ],
    dimensionWeights: {
      0: { energy: 20, warmth: 60, rhythm: 30, depth: 65, luminance: 60, complexity: 25 },
      1: { energy: 85, warmth: 70, rhythm: 80, depth: 35, luminance: 70, complexity: 55 },
      2: { energy: 45, warmth: 40, rhythm: 50, depth: 90, luminance: 45, complexity: 75 },
      3: { energy: 90, warmth: 50, rhythm: 85, depth: 50, luminance: 55, complexity: 85 },
    },
  },
];
