import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service | YourAuraScore',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black">
      <nav className="flex items-center justify-between px-6 py-5">
        <Link href="/" className="text-white font-bold text-lg tracking-tight">
          YourAura<span className="text-purple-400">Score</span>
        </Link>
      </nav>

      <main className="max-w-2xl mx-auto px-6 py-12">
        <h1 className="text-white text-3xl font-bold mb-8">Terms of Service</h1>

        <div className="space-y-6 text-white/70 text-sm leading-relaxed">
          <p>Last updated: February 2026</p>

          <section>
            <h2 className="text-white text-lg font-semibold mb-2">Acceptance of Terms</h2>
            <p>
              By accessing and using this website, you accept and agree to be bound by
              these Terms of Service. If you do not agree, please do not use the site.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-semibold mb-2">Description of Service</h2>
            <p>
              YourAuraScore provides a personality quiz that generates a unique aura
              visualization. The quiz is for entertainment purposes only and should not
              be considered a psychological assessment.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-semibold mb-2">Digital Products</h2>
            <p>
              Purchases of digital downloads (HD wallpapers, animated wallpapers, personality
              reports) are final and non-refundable, as these are instantly delivered digital
              goods. Each product is uniquely generated for your quiz results.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-semibold mb-2">Merchandise</h2>
            <p>
              Physical merchandise is fulfilled by Printful. Shipping, returns, and product
              quality are governed by Printful&apos;s terms of service and policies.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-semibold mb-2">Intellectual Property</h2>
            <p>
              The aura visualization generated by your quiz is licensed to you for personal
              use. You may use it as your wallpaper, share it on social media, and print it
              for personal enjoyment. Commercial use of the generated artwork requires
              written permission.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-semibold mb-2">Limitation of Liability</h2>
            <p>
              YourAuraScore is provided &quot;as is&quot; without warranty of any kind. We are
              not liable for any damages arising from the use of this service.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-semibold mb-2">Contact</h2>
            <p>
              For questions about these terms, contact us at info@alstonanalystics.com.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
